[package]
distribution = "2201.10.0"
org = "ballerinax"
name = "ibm.ctg"
version = "@toml.version@"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["IBM", "CICS", "CTG", "Mainframe"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-ibm.ctg"

[platform.java17]
graalvmCompatible = true
