[package]
distribution = "2201.10.0"
org = "ballerinax"
name = "ibm.ctg"
version = "@toml.version@"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["IBM", "CICS", "CTG", "Mainframe"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-ibm.ctg"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.lib"
artifactId = "ibm.ctg-native"
version = "@project.version@"
path = "../native/build/libs/ibm.ctg-native-@project.version@.jar"

[[platform.java17.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-databind"
version = "@jackson.version@"
path = "./lib/jackson-databind-@jackson.version@.jar"

[[platform.java17.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-core"
version = "@jackson.version@"
path = "./lib/jackson-core-@jackson.version@.jar"

[[platform.java17.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-annotations"
version = "@jackson.version@"
path = "./lib/jackson-annotations-@jackson.version@.jar"

[[platform.java17.dependency]]
groupId = "commons-io"
artifactId = "commons-io"
version = "@commons.io.version@"
path = "./lib/commons-io-@commons.io.version@.jar"

[[platform.java17.dependency]]
groupId = "org.apache.httpcomponents.core5"
artifactId = "httpcore5"
version = "@http.core.version@"
path = "./lib/httpcore5-@http.core.version@.jar"

[[platform.java17.dependency]]
groupId = "org.apache.httpcomponents.core5"
artifactId = "httpcore5-h2"
version = "@http.core.version@"
path = "./lib/httpcore5-h2-@http.core.version@.jar"

[[platform.java17.dependency]]
groupId = "org.apache.httpcomponents.client5"
artifactId = "httpclient5"
version = "@http.client.version@"
path = "./lib/httpclient5-@http.client.version@.jar"

[[platform.java17.dependency]]
groupId = "org.apache.geronimo.specs"
artifactId = "geronimo-j2ee-connector_1.6_spec"
version = "@geronimo.j2ee.version@"
path = "./lib/geronimo-j2ee-connector_1.6_spec-@geronimo.j2ee.version@.jar"
