[package]
distribution = "2201.10.0"
org = "ballerinax"
name = "ibm.ctg"
version = "0.1.0"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["IBM", "CICS", "CTG", "Mainframe"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-ibm.ctg"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.lib"
artifactId = "ibm.ctg-native"
version = "0.1.0-SNAPSHOT"
path = "../native/build/libs/ibm.ctg-native-0.1.0-SNAPSHOT.jar"
