name: PR Build

on: pull_request

jobs:
    ubuntu-build:
        name: Build
        runs-on: ubuntu-latest
        concurrency:
          group: ${{ github.head_ref }}-ubuntu-build
          cancel-in-progress: true
        steps:
            -   name: Checkout Repository
                uses: actions/checkout@v3

            - name: Get Ballerina Version
              run: |
                BAL_VERSION=$(grep -w 'ballerinaLangVersion' gradle.properties | cut -d= -f2 | rev | cut --complement -d- -f1 | rev) 
                if [ -z "$BAL_VERSION" ]; then
                  BAL_VERSION="latest"
                fi
                echo "BAL_VERSION=$BAL_VERSION" >> $GITHUB_ENV
                echo "Ballerina Version: $BAL_VERSION"

            - name: Set Up Ballerina
              uses: ballerina-platform/setup-ballerina@v1.1.0
              with:
                version: ${{ env.BAL_VERSION }}

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    distribution: 'temurin'
                    java-version: 17.0.7
            
            -   name: Set ENV Variables
                run: |
                  echo -e '${{ toJson(secrets) }}' | jq -r 'to_entries[] | .key + "=" + .value' >> $GITHUB_ENV 

            -   name: Build the Package
                env:
                    packageUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
                    packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
                run: |
                  ./gradlew build -x test
                  ./gradlew test

            -   name: Generate Codecov Report
                uses: codecov/codecov-action@v3
